import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../components/Navbar'
import { minifyRecords, table } from './api/utils/Airtable'
import Todo from '../components/Todo'
import {TodosContext} from '../contexts/TodosContext'
import {useEffect, useContext} from 'react'
import { getSession } from '@auth0/nextjs-auth0'

export default function Home({initialTodos, user}) {
  const {todos, setTodos} = useContext(TodosContext)
  useEffect(() => {
    setTodos(initialTodos)
  }, [])
  
  return (
    <div >
      <Head>
        <title>Authenticated TODO App </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar user={user}/>
      <main>
        <h1>ToDo App</h1>
        {todos && todos.map(todo => (
          <ul>
            <Todo key={todo.id} todo={todo}/>
          </ul>
        ))}
      </main>
      <a href="/api/auth/login">Login</a>;
    </div>
  )
}


export async function getServerSideProps(context) {
  // const session = await auth0.getSession(context.req);

  const session = await getSession(context.req, context.res)

  try {
    const todos = await table.select({}).firstPage();
    return {
      props: {
        initialTodos: minifyRecords(todos),
        user: session?.user || null, // wow, this works. 
      }
    }
  } catch (err) {
    console.error(err)
    return {
      props: {
        err: "Something went wrong"
      }
    }
  }
}